name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Installing wheel
        run: pip3 install wheel

      - name: Build wheels
        run: python3 setup.py bdist_wheel --universal --dist-dir=wheels

      - name: Installing lightBlue
        run: python3 setup.py install

      - name: Zipping lightAquaBlue
        run: zip LightAquaBlue.zip /Library/Frameworks/LightAquaBlue -r

      - uses: actions/upload-artifact@v2
        with:
          name: asset-for-down
          path: ./wheels/*.whl
      
      - uses: actions/upload-artifact@v2
        with:
          name: LightAquaBlue
          path: ./LightAquaBlue.zip
